config/routes.rb
Rails.application.routes.draw do


  root "statique#home"
  get "/confirm", to: "statique#confirm"
  get "/club", to: "statique#club"

  get "sessions/new"

  get "/contact", to: "statique#contact"
  get "/team", to: "statique#team"
  get "/services", to: "statique#services"

  get "/signup", to: "users#new"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"


  resources :users

end

app/models/ability.rb
class Ability
    include CanCan::Ability

    def initialize(user)
      user ||= User.new
  
      alias_action :create, :read, :update, :destroy, to: :crud # Pour ne pas se répéter
  
      can [:create], User # Seul les actions :index, :show sont accessible publiquement
      
      if user.id
        can [:crud], User, {id: user.id} 
      end
  
      #if user.admin?
        #can :manage, :all # L'administrateur peut tout modifier
      #end
  
    end
  end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
    validates :firstname, presence: true, length: {maximum: 50}
    validates :lastname, presence: true, length: {maximum: 50}
    validates :email, presence: true, length: {maximum: 250}, uniqueness: {case_sensitive: false}
    has_secure_password
    validates :password, presence: true, length: {minimum: 6}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  add_flash_types :danger, :info, :warning, :success, :primary
  include SessionsHelper
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
        redirect_to root_url
        flash[:primary] = "Vous êtes connecté ! "
    else
      flash[:danger] = 'Email ou Mot de passe invalide ! '
      render "new"
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
    flash[:primary] = "Vous êtes déconnecté ! "
  end
end

app/controllers/statique_controller.rb
class StatiqueController < ApplicationController
  def home
  end

  def confirm 
  end

  def club
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_resource
  authorize_resource

  def index
  end

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to confirm_path
    else 
      render "new"
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update 
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      redirect_to @user
    else
      render "edit"
    end
  end

  def destroy
    User.find(params[:id]).destroy
    redirect_to user_url
  end

  private 
  
  def user_params
    params.require(:user).permit(:firstname, :lastname, :email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

    def log_in(user)
        session[:user_id] = user.id
    end

    def current_user
        if session[:user_id]
          @current_user ||= User.find_by(id: session[:user_id])
        end
      end

      def logged_in?
        !current_user.nil?
      end

      def log_out
        session.delete(:user_id)
        @current_user = nil
      end



end

app/helpers/statique_helper.rb
module StatiqueHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_flashmessage.html.erb
<% flash.each do |name, msg| %>
    <div class="alert alert-<%= name %>">
      <%= msg %>
    </div>
<% end %>

app/views/layouts/_footer.html.erb
<div class="footer">
    <div class="footer-container">
        <div class="footer-heart-container">
            <p class="footer-heart">Made with  <i  id="heart" class="em em-beers"></i>  in Strasbourg</p>
        </div>
    </div>
</div>

app/views/layouts/_header.html.erb
<% if logged_in? %>
<div class="header">
    <div class="header-container">
        <h1 class="header-title"><a href="/">TDD Project</a><i class="em em-wrench"></i></h1>
        <div class="header-link">
            <a class="header-link" href=""><%= link_to "Home",root_path %> <i class="fas fa-home"></i></a>
            <a class="header-link" href=""><%= link_to "Club", club_path %><i class="fas fa-users"></i></a>
            <a class="header-link" href=""><%= link_to "Profil", current_user %><i class="fas fa-user"></i></a>
            <a class="header-link" href=""><%= link_to "Déconnexion", logout_path, method: :delete %><i class="far fa-trash-alt"></i></a>
        </div>
    </div>
</div>

<% else %>
<div class="header">
    <div class="header-container">
        <h1 class="header-title"><a href="/">TDD Project</a><i class="em em-wrench"></i></h1>
        <div class="header-link">
            <a class="header-link" href="/login">Connexion <i class="fas fa-align-right"></i></a>
            <a class="header-link" href="/signup">Inscription <i class="fas fa-book"></i></a>
            <a class="header-link" href="/">Home <i class="fas fa-home"></i></a>
        </div>
    </div>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | TDD Project</title>
    <%= favicon_link_tag asset_path('1f527.png') %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.2/css/all.css" integrity="sha384-/rXc/GQVaYpyDdyxK+ecHPVYJSN9bmVFBvjA/9eOB+pb3F2w2N6fc5qB9Ew5yIns" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    <link href="https://afeld.github.io/emoji-css/emoji.css" rel="stylesheet">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= render 'layouts/flashmessage' %>
      <div class="container">
        <%= yield %>
      </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/statique/club.html.erb
<% if logged_in? %>
<h4 class="main-title">Bienvenue <strong><%= current_user.firstname %>. </strong>Connecté en tant que  <strong><%= current_user.email %></strong>
<%= link_to "Déconnexion", logout_path, method: :delete, class: "btn btn-primary" %></h4>
<h1>Voilà tout les membres du club : </h1>
<% User.all.each do |user| %>
    <div class="card">
      <div class="card-body">
        <h4>Utilisateur n°<%= user.id%></h4>
        <h4>Nom <strong> <%= user.firstname%> </h4> </strong>
        <h4>Prénom <strong> <%= user.lastname%> </h4> </strong>
        <a href= "<%= user_path(user.id)%>" class="btn btn-primary">Voir</a>
      </div>
    </div>
  <% end %>
<% else %>
<div class="container-cent">
	<h1 class="main-title">TDD Project</h1>
</div>
<h4 class="main-title"><i class="em em-arrow_double_down"></i> Pour accéder au Club vous devez vous <strong>Connectez</strong> ou bien vous <strong>Inscrire</strong> <i class="em em-arrow_double_down"></i><h4>
	<%=  link_to "Inscription", signup_path , class: "btn btn-success", id: "ins" %>  
	<%=  link_to "Connexion", login_path , class: "btn btn-success ", id: "con" %> 
<% end %>

app/views/statique/confirm.html.erb
<div class="container-cent">
<h1 class="main-title">Ton Compte à bien était crée <i class="em em-white_check_mark"></i> </h1>
<h3 class="main-title">Maintenant tu peux te connecter ! <h3>
<%=  link_to "Connexion", login_path , class: "btn btn-success ", id: "con" %> 
</div>

app/views/statique/home.html.erb
<% provide(:title, "Home") %>
<div class="container-cent">
	<h1 class="colf main-title">TDD Project</h1>
</div>
<% if logged_in? %>
<h4 class="main-title">Bienvenue <strong><%= current_user.firstname %>. </strong>Connecté en tant que  <strong><%= current_user.email %>.</strong>
<%= link_to "Déconnexion", logout_path, method: :delete, class: "btn btn-primary" %></h4> <br>
<%= link_to "Voir le Club", club_path, class: "btn btn-primary" %></h4>
<% else %>
<h4 class="main-title"><i class="em em-arrow_double_down"></i> Pour utiliser TDD Project vous devez vous <strong>Connectez</strong> ou bien vous <strong>Inscrire</strong> <i class="em em-arrow_double_down"></i><h4>
	<%=  link_to "Inscription", signup_path , class: "btn btn-success", id: "ins" %>  
	<%=  link_to "Connexion", login_path , class: "btn btn-success ", id: "con" %> 
<% end %>

app/views/users/edit.html.erb
<% provide(:title, "Editer mon profil") %>
<% if logged_in? %>
<h1 class="main-title">Mettre à jour votre profil</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>

      <%= f.label :firstname %>
      <%= f.text_field :firstname, class: 'form-control' %>

      <%= f.label :lastname %>
      <%= f.text_field :lastname, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Mettre à jour mon Profil",  class: "btn btn-primary" %>
    <% end %>

  </div>
</div>
<% else %>
<div class="container-cent">
<h1 class="main-title"> <i class="em em-warning"></i> Connectez vous !  <i class="em em-warning"></i> </h1>
</div>
<% end %>

app/views/users/new.html.erb
<% provide(:title, "S'enregistrer") %>

<h1 class="main-title">S'Inscrire</h1>
<div class="container">
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>

      <%= f.label :firstname, "Prénom" %>
      <%= f.text_field :firstname, class: 'form-control' %>

      <%= f.label :lastname, "Nom"%>
      <%= f.text_field :lastname, class: 'form-control' %>

      <%= f.label :email, "Email"%>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password, "Mot de Passe" %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Créer mon compte", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.firstname) %>
<% if logged_in? %>
<div class="container-cent">
  <h1>Bonjour <strong> <%= @user.firstname%> <i class="em em-blush"></i> </strong> ! </h1>
  <h3>Voilà quelques informations sur ton Profil : </h3>
  <h2>Prénom : <%= @user.firstname%> </h2>
  <h2>Nom : <%= @user.lastname%> </h2>
  <h2>Email : <%= @user.email%> </h2>
  
  <%= link_to "Editer mon Profil", edit_user_path, class: "btn btn-info "%>
  <%= link_to "Déconnexion", logout_path,class: "btn btn-danger ", method: :delete %>
</div>
</div>
<% else %>
<div class="container-cent">
<h1 class="main-title"> <i class="em em-warning"></i> Connectez vous !  <i class="em em-warning"></i> </h1>
</div>
<% end %>